import { createHash } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fromRoot = (...parts) => path.join(root, ...parts);
const toPosix = (value) => value.split(path.sep).join("/");

const readText = (file) => readFile(fromRoot(file), "utf8");
const config = JSON.parse(await readText("site.config.json"));
const pageTemplate = await readText("src/templates/page.html");
const homeTemplate = await readText("src/templates/home.html");

const generatedNotice = "<!-- Generated by scripts/build.mjs. Edit site.config.json, src/content, src/templates, or src/styles instead. -->";

const escapeHtml = (value) => String(value)
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;");

const fill = (template, replacements) => Object.entries(replacements)
  .reduce((output, [key, value]) => output.replaceAll(`{{${key}}}`, value), template);

const cleanHtml = (html) => html
  .replace(/[ \t]+$/gm, "")
  .replace(/\n{3,}/g, "\n\n")
  .trimEnd();

const relativePrefix = (output) => {
  const directory = path.posix.dirname(output);
  if (directory === ".") return "";
  return "../".repeat(directory.split("/").length);
};

const relativePageHref = (fromOutput, toOutput) => {
  const relative = path.posix.relative(path.posix.dirname(fromOutput), toOutput);
  return relative || path.posix.basename(toOutput);
};

const validateConfig = () => {
  const courseIds = new Set();
  const outputs = new Set();

  for (const course of config.courses) {
    if (courseIds.has(course.id)) throw new Error(`Duplicate course id: ${course.id}`);
    courseIds.add(course.id);

    if (!course.pages.some((page) => page.output === course.entry)) {
      throw new Error(`Course entry is not declared as a page: ${course.entry}`);
    }

    for (const page of course.pages) {
      if (outputs.has(page.output)) throw new Error(`Duplicate page output: ${page.output}`);
      outputs.add(page.output);
    }
  }
};

validateConfig();

const assetSources = {
  siteCss: "src/styles/site.css",
  codeCss: "src/styles/code-blocks.css",
  themeInit: "src/client/theme-init.js",
  headerJs: "src/client/header.js",
  tocJs: "src/client/toc.js",
  homeJs: "src/client/home.js",
  codeJs: "src/client/code-blocks.js",
};

const buildDirectory = fromRoot("assets/build");
await rm(buildDirectory, { recursive: true, force: true });
await mkdir(buildDirectory, { recursive: true });

const assetManifest = {};
for (const [name, source] of Object.entries(assetSources)) {
  const content = await readFile(fromRoot(source));
  const extension = path.extname(source);
  const baseName = path.basename(source, extension);
  const hash = createHash("sha256").update(content).digest("hex").slice(0, 10);
  const outputName = `${baseName}.${hash}${extension}`;
  await writeFile(path.join(buildDirectory, outputName), content);
  assetManifest[name] = `assets/build/${outputName}`;
}
await writeFile(
  path.join(buildDirectory, "manifest.json"),
  `${JSON.stringify(assetManifest, null, 2)}\n`,
);

const icons = {
  grid: '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="4" width="6" height="6" rx="1"></rect><rect x="14" y="4" width="6" height="6" rx="1"></rect><rect x="4" y="14" width="6" height="6" rx="1"></rect><rect x="14" y="14" width="6" height="6" rx="1"></rect></svg>',
  light: '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"></circle><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.65 17.65l1.42 1.42M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.65 6.35l1.42-1.42"></path></svg>',
  dark: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 15.3A8.5 8.5 0 0 1 8.7 3.5 8.5 8.5 0 1 0 20.5 15.3Z"></path></svg>',
  auto: '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="13" rx="2"></rect><path d="M8 21h8M12 17v4"></path></svg>',
};

const renderThemeControl = () => `
        <div class="theme-control" data-theme-control data-popover>
          <button class="theme-trigger" type="button" aria-label="自适应模式" aria-haspopup="menu" aria-expanded="false" aria-controls="theme-menu" title="自适应模式" data-theme-trigger data-popover-trigger>
            <span class="theme-icon theme-icon-light">${icons.light}</span>
            <span class="theme-icon theme-icon-dark">${icons.dark}</span>
            <span class="theme-icon theme-icon-auto">${icons.auto}</span>
          </button>
          <div class="theme-menu" id="theme-menu" role="menu" data-popover-panel hidden>
            <button class="theme-option" type="button" role="menuitemradio" aria-label="日间模式" aria-checked="false" title="日间模式" data-theme-option="light">${icons.light}</button>
            <button class="theme-option" type="button" role="menuitemradio" aria-label="夜间模式" aria-checked="false" title="夜间模式" data-theme-option="dark">${icons.dark}</button>
            <button class="theme-option" type="button" role="menuitemradio" aria-label="自适应模式" aria-checked="true" title="自适应模式" data-theme-option="auto">${icons.auto}</button>
          </div>
        </div>`;

const renderCourseMenu = (prefix, currentCourse) => {
  const items = config.courses.map((course) => `
              <a class="course-switcher-item${course.id === currentCourse.id ? " active" : ""}" href="${prefix}${course.entry}"${course.id === currentCourse.id ? ' aria-current="page"' : ""}>
                <span class="course-switcher-dot" aria-hidden="true"></span>
                <span><strong>${escapeHtml(course.menuLabel)}</strong><small>${escapeHtml(course.description)}</small></span>
              </a>`).join("");

  return `
        <div class="course-menu" data-popover>
          <button class="course-menu-button" type="button" aria-label="课程切换" aria-haspopup="menu" aria-expanded="false" aria-controls="course-menu-panel" title="课程切换" data-popover-trigger>${icons.grid}</button>
          <div class="course-menu-panel" id="course-menu-panel" data-popover-panel hidden>
            <div class="course-menu-label">COURSES</div>
            <nav class="course-switcher" aria-label="课程切换">${items}
            </nav>
          </div>
        </div>`;
};

const renderGithubLink = (prefix) => `
        <a class="github-link" href="${config.site.githubUrl}" aria-label="GitHub 项目" title="GitHub 项目">
          <img class="github-mark-light" src="${prefix}assets/github-mark.png" alt="" />
          <img class="github-mark-dark" src="${prefix}assets/github-mark-dark.png" alt="" />
        </a>`;

const renderHeader = ({ prefix, currentCourse = null }) => `
    <header class="site-header">
      <div class="header-inner">
        <a class="brand" href="${prefix}index.html"><span>AAI</span> 学习手册</a>
        <div class="header-actions">${renderThemeControl()}${currentCourse ? renderCourseMenu(prefix, currentCourse) : renderGithubLink(prefix)}
        </div>
      </div>
    </header>`;

const renderHead = ({ prefix, code = false }) => {
  const codeStyle = code
    ? `\n    <link rel="stylesheet" href="${prefix}${assetManifest.codeCss}" />`
    : "";
  return `<link rel="icon" type="image/svg+xml" href="${prefix}assets/favicon.svg" />
    <script src="${prefix}${assetManifest.themeInit}"></script>
    <link rel="stylesheet" href="${prefix}${assetManifest.siteCss}" />${codeStyle}`;
};

const renderScripts = ({ prefix, home = false, course = false, code = false }) => {
  const scripts = [`<script src="${prefix}${assetManifest.headerJs}" defer></script>`];
  if (home) scripts.push(`<script src="${prefix}${assetManifest.homeJs}" defer></script>`);
  if (course) scripts.push(`<script src="${prefix}${assetManifest.tocJs}" defer></script>`);
  if (code) scripts.push(`<script src="${prefix}${assetManifest.codeJs}" defer></script>`);
  return scripts.join("\n    ");
};

const renderToc = (course, currentPage) => {
  const pages = course.pages.map((page) => {
    const active = page.output === currentPage.output;
    const pageSections = page.subsections ?? config.sections;
    const sections = pageSections.map((section) => `
              <a href="#${section.id}" data-toc-section="${section.id}">${escapeHtml(section.label)}</a>`).join("");

    return `
          <div class="chapter-group${active ? " active" : ""}" data-chapter-group>
            <a class="chapter-link${active ? " active" : ""}"${active ? ' aria-current="page"' : ""} href="${relativePageHref(currentPage.output, page.output)}">${escapeHtml(page.navLabel)}</a>
            <div class="chapter-subnav"${active ? "" : ' aria-hidden="true" inert'}>
              <div class="chapter-subnav-inner">${active ? sections : ""}
              </div>
            </div>
          </div>`;
  }).join("");

  return `<aside class="toc">
        <div class="toc-title">${escapeHtml(course.tocTitle)}</div>
        <nav class="chapter-links" aria-label="${escapeHtml(course.name)}页面">${pages}
        </nav>
      </aside>`;
};

const renderChapterNav = (course, currentPage, prefix) => {
  if (course.pages.length < 2) return "";

  const index = course.pages.findIndex((page) => page.output === currentPage.output);
  const previous = course.pages[index - 1];
  const next = course.pages[index + 1];
  const previousLink = previous
    ? `<a href="${relativePageHref(currentPage.output, previous.output)}">← ${escapeHtml(previous.navLabel)}</a>`
    : "<span></span>";
  const nextLink = next
    ? `<a href="${relativePageHref(currentPage.output, next.output)}">${escapeHtml(next.navLabel)} →</a>`
    : `<a href="${prefix}index.html">返回课程首页 →</a>`;

  return `
        <nav class="chapter-nav" aria-label="上一页和下一页">
          ${previousLink}${nextLink}
        </nav>`;
};

const courseRows = config.courses.map((course) => `
        <a class="course-row" href="${course.entry}">
          <span class="course-row-index">${escapeHtml(course.index)}</span>
          <span class="course-row-content"><strong>${escapeHtml(course.name)}</strong><small>${escapeHtml(course.description)}</small></span>
        </a>`).join("");

const homeHtml = fill(homeTemplate, {
  HEAD: renderHead({ prefix: "" }),
  TITLE: escapeHtml(config.site.title),
  HEADER: renderHeader({ prefix: "" }),
  COURSE_LIST: courseRows,
  SCRIPTS: renderScripts({ prefix: "", home: true }),
});
await writeFile(fromRoot("index.html"), `${cleanHtml(`${generatedNotice}\n${homeHtml}`)}\n`);

for (const course of config.courses) {
  for (const page of course.pages) {
    const prefix = relativePrefix(page.output);
    const sourceContent = await readText(page.content);
    const content = sourceContent.replace(
      /\s*<\/main>\s*$/,
      `${renderChapterNav(course, page, prefix)}\n      </main>`,
    );
    const html = fill(pageTemplate, {
      HEAD: renderHead({ prefix, code: page.code }),
      TITLE: escapeHtml(config.site.title),
      COURSE_ID: escapeHtml(course.id),
      HEADER: renderHeader({ prefix, currentCourse: course }),
      TOC: renderToc(course, page),
      CONTENT: content.trim(),
      SCRIPTS: renderScripts({ prefix, course: true, code: page.code }),
    });
    const outputPath = fromRoot(page.output);
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, `${cleanHtml(`${generatedNotice}\n${html}`)}\n`);
  }
}

const redirectHtml = `${generatedNotice}
<!doctype html>
<html lang="zh-CN" data-color-mode="auto">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta http-equiv="refresh" content="0; url=../index.html" />
    <script src="../${assetManifest.themeInit}"></script>
    <title>${escapeHtml(config.site.title)}</title>
  </head>
  <body>
    <p>正在打开 <a href="../index.html">${escapeHtml(config.site.title)}</a>……</p>
  </body>
</html>
`;
await mkdir(fromRoot("outputs"), { recursive: true });
await writeFile(fromRoot("outputs/aai-learning-dashboard.html"), `${cleanHtml(redirectHtml)}\n`);

console.log(`Built ${config.courses.reduce((sum, course) => sum + course.pages.length, 0) + 2} HTML files.`);
console.log(`Generated assets: ${Object.values(assetManifest).map(toPosix).join(", ")}`);
