import { access, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const config = JSON.parse(await readFile(path.join(root, "site.config.json"), "utf8"));
const generatedNotice = "Generated by scripts/build.mjs";
const errors = [];

const pages = [
  "index.html",
  ...config.courses.flatMap((course) => course.pages.map((page) => page.output)),
  "outputs/aai-learning-dashboard.html",
];

const exists = async (file) => {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
};

const localReference = /\b(?:href|src)="([^"]+)"/g;
const idPattern = /\bid="([^"]+)"/g;

for (const page of pages) {
  const absolutePage = path.join(root, page);
  if (!(await exists(absolutePage))) {
    errors.push(`${page}: generated page is missing`);
    continue;
  }

  const html = await readFile(absolutePage, "utf8");
  if (!html.includes(generatedNotice)) errors.push(`${page}: generated-file notice is missing`);
  if (html.includes("?v=")) errors.push(`${page}: contains a manual cache version`);
  if ((html.match(/<main\b/g) || []).length !== (html.match(/<\/main>/g) || []).length) {
    errors.push(`${page}: main element is not balanced`);
  }

  const ids = new Set([...html.matchAll(idPattern)].map((match) => match[1]));
  for (const [, reference] of html.matchAll(localReference)) {
    if (/^(?:https?:|mailto:|tel:|data:)/.test(reference)) continue;

    const [targetPath, hash = ""] = reference.split("#");
    const withoutQuery = targetPath.split("?")[0];
    const resolved = withoutQuery
      ? path.resolve(path.dirname(absolutePage), withoutQuery)
      : absolutePage;

    if (!(await exists(resolved))) {
      errors.push(`${page}: missing local target ${reference}`);
      continue;
    }

    if (hash && resolved === absolutePage && !ids.has(hash)) {
      errors.push(`${page}: missing anchor #${hash}`);
    }
  }
}

const courseIds = config.courses.map((course) => course.id);
if (new Set(courseIds).size !== courseIds.length) errors.push("site.config.json: duplicate course id");

for (const course of config.courses) {
  if (!course.pages.some((page) => page.output === course.entry)) {
    errors.push(`site.config.json: ${course.id} entry is not one of its pages`);
  }
  for (const page of course.pages) {
    if (!(await exists(path.join(root, page.content)))) {
      errors.push(`site.config.json: missing source content ${page.content}`);
    }
  }
}

if (errors.length) {
  console.error(errors.map((error) => `- ${error}`).join("\n"));
  process.exitCode = 1;
} else {
  console.log(`Checked ${pages.length} generated pages and ${config.courses.length} courses.`);
}
